site_name: Manuais — Rede Aviação
site_description: Passo a passo para usar o sistema de vagas de trabalho na aviação.
site_url: https://aerotd.github.io/vagas-manual/
edit_uri: https://github.com/AeroTD/vagas-manual/edit/main/docs/

theme:
  name: material
  language: pt-BR
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.footnotes
    - content.tabs # habilita abas
    - content.tabs.link # permite linkar a aba
    - content.images.preview # habilita zoom/preview de imagens
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: blue
  favicon: imagens/favicon.png
  logo: imagens/rede_aviacao_logo.png

nav:
  - Início: index.md
  - Autenticação:
      - Login: autenticacao/login.md
      - Registro: autenticacao/registro.md
      - Recuperar Senha: autenticacao/recuperar-senha.md
      # - Verificar E-mail: autenticacao/verificar-email.md
  - Para Candidatos:
      - Cadastrar Currículo: candidato/curriculo.md
      - Candidatar-se a Vaga: candidato/candidatar-vagas.md
      - Edição de Perfil do Candidato: candidato/edicao-perfil-candidato.md
      - Chat de Mensagens: interacao/chat.md
  - Para Empresas:
      - Dashboard da Empresa: empresa/dashboard.md
      - Edição do Perfil de Recrutador: empresa/edicao-perfil-empresa.md
      - Vagas: empresa/vagas.md
      - Gestão do Processo Seletivo: empresa/gestao-processo-seletivo.md
      # - Criação de Vagas: empresa/criar-vaga.md
      # - Editar Vagas: empresa/editar-vagas.md
      - Busca de Candidatos: empresa/busca-candidatos.md
      - Chat de Mensagens: interacao/chat.md
      - Editar Página da Empresa: empresa/editar-pagina-empresa.md
      - Convite Colaborador: empresa/convite-colaborador.md
      
      

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
      locale: pt_BR
      enable_git_follow: false
  - glightbox:
      effect: zoom

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AeroTD/vagas-manual

extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap

extra_javascript:
  # Lucide (CDN)
  - https://unpkg.com/lucide@latest/dist/umd/lucide.min.js
  - javascripts/lucide-init.js
